# Generated by Django 3.1.2 on 2020-11-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201106_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='funds',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
