# Generated by Django 3.1.2 on 2020-11-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201106_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='funds',
            field=models.FloatField(default=1000),
        ),
    ]
