# Generated by Django 3.1.2 on 2020-11-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201106_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount_available',
            field=models.IntegerField(default=0),
        ),
    ]
